### ISSUE TITLE
Create display for Amenities

### ISSUE THREAD

**Issue by cogmind** [Doorsfan/ClearBnB#38]
In light of this task requiring more finalized values in terms of the JSON structure and clarity on the integration of the
DB structure - We have chosen to postpone this task - until the DB related matters have been resolved

**Comment by Doorsfan** [comment]
In light of this task requiring more finalized values in terms of the JSON structure and clarity on the integration of the
DB structure - We have chosen to postpone this task - until the DB related matters have been resolved
